### ISSUE TITLE
Error Deserializing TokenCache

### ISSUE THREAD

**Issue by agent354** [Azure-Samples/active-directory-webapp-webapi-multitenant-openidconnect-aspnetcore#1]
Pulled down current release, updated client id/secret and url to point to custom api and seem to get the below error no matter what I do.  What am I missing?  It is a bug in the JSON code to not be able to handle some component of the TokenCache class?

An exception of type 'System.MissingMethodException' occurred in System.Private.CoreLib.ni.dll but was not handled in user code

Additional information: No parameterless constructor defined for this object.

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API
