### ISSUE TITLE
This sample is very old

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/active-directory-webapp-webapi-multitenant-openidconnect-aspnetcore#10]
This sample is very old. It uses ASP.NET Core 1.x and ADAL 3.10 (!!!). I wasn't able to get it to run on modern .net core

@jmprieur  - this sample is now referenced from the official https://docs.microsoft.com/en-gb/azure/active-directory/develop/sample-v1-code

**Comment by ravensorb** [comment]
+1 Please at least upgrade this to a released version of .net core

**Comment by bgavrilMS** [comment]
@ravensorb - have a look at this sample which is maintained and actively developed https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API
