### ISSUE TITLE
error when trying to run in IISExpress

### ISSUE THREAD

**Issue by markti** [Azure-Samples/active-directory-webapp-webapi-multitenant-openidconnect-aspnetcore#2]
An error occurred attempting to determine the process id of dotnet.exe. Keep getting this error. Unable to get it running on the default launch settings or any new https launch settings.

**Comment by Gimly** [comment]
I had the same issue, it seems to be linked to an issue with the certificate. I fixed it by following this method https://support.microsoft.com/en-us/help/3180222/warnings-about-an-untrusted-certificate-after-you-install-visual-studio-2015-update-3

**Comment by gsacavdm** [comment]
Thanks for chiming in @Gimly. Yes, getting https up and running on dot net core can be tricky at time. That article has great tips on how to get going.
