### ISSUE TITLE
Not authorized on tenant

### ISSUE THREAD

**Issue by coldWire79** [Azure-Samples/active-directory-webapp-webapi-multitenant-openidconnect-aspnetcore#5]
When I run this application and click signup I'm redirected to login.  Upon entering the login credentials for a global admin user on a test tenant I get the following login screen error.

AADSTS50020: User account [username] from identity provider 'live.com' does not exist in tenant [tenant] and cannot access the application [app id] in that tenant. The account needs to be added as an external user in the tenant first. 

Correct me if I'm wrong; but isn't the idea of the signup process to on board new tenants? Or have I miscofigured something?

**Comment by TiagoBrenck** [comment]
Here is a sample showing how to onboard tenants: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-3-Multi-Tenant

Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API
