### ISSUE TITLE
Updating Microsoft.AspNetCore.Authentication.OpenIdConnect from 1.0.2 to 1.1.2

### ISSUE THREAD

**Issue by blyw** [Azure-Samples/active-directory-webapp-webapi-multitenant-openidconnect-aspnetcore#8]
Updating to version 1.1.2 on VS 2017 causes failure to retrieve id_token. Another similar ASP.NET Core also suffers from this issue. For solution, see: https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/issues/15

**Comment by BenjaminAbt** [comment]
Thank you. for your update. Saved me a lot of time!

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API
